name: UsedCars With CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: usedcars_test
          MYSQL_USER: usedcarsUser
          MYSQL_PASSWORD: usedcarsPass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Wait for MariaDB to be ready
        run: |
          echo "Waiting for MariaDB..."
          until mysql -h 127.0.0.1 -u root -prootpassword -e "SELECT 1"; do
            sleep 2
          done
      
      - name: Build with Maven
        run: mvn verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://127.0.0.1:3306/usedcars_test
          SPRING_DATASOURCE_USERNAME: usedcarsUser
          SPRING_DATASOURCE_PASSWORD: usedcarsPass
      
      - uses: actions/upload-artifact@v4
        with:
          name: UsedCars
          path: target/*.jar
